#!/bin/bash

# Figure out where it is installed
FWDIR="$(cd `dirname $0`; pwd)"

# Export this as Yosemite_HOME
export YOSEMITE_HOME="$FWDIR"
RUNNER="${JAVA_HOME}/bin/java"

if [ -z "$YOSEMITE_MEM" ] ; then
  YOSEMITE_MEM="512m"
fi
export YOSEMITE_MEM

# Set JAVA_OPTS to be able to load native libraries and to set heap size
JAVA_OPTS="$YOSEMITE_JAVA_OPTS"
JAVA_OPTS+=" -Xms$YOSEMITE_MEM -Xmx$YOSEMITE_MEM"
# Load extra JAVA_OPTS from conf/java-opts, if it exists
if [ -e $FWDIR/conf/java-opts ] ; then
  JAVA_OPTS+=" `cat $FWDIR/conf/java-opts`"
fi
export JAVA_OPTS

CORE_DIR="$FWDIR"

# Build up classpath
CLASSPATH="$YOSEMITE_CLASSPATH"
CLASSPATH+=":$FWDIR/conf"
CLASSPATH+=":$CORE_DIR/target/classes"
CLASSPATH+=":$CORE_DIR/target/coflowsim-0.2.0-SNAPSHOT.jar"

export CLASSPATH


exec "$RUNNER" -cp "$CLASSPATH" $EXTRA_ARGS "$@"
